### ISSUE TITLE
Nest API - Error: Received empty response from request

### ISSUE THREAD

**Issue by ecomix** [gboudreau/nest-api#105]
Hi,

Since today i'm receiving this message from google when I try to create a Nest instance:

  $nest = new Nest(NULL, NULL, $issue_token, $cookies);

Error: Received empty response from request to https://accounts.google.com/o/oauth2/iframerpc?action=...

Does anyone has the same problem?

B.R
Miguel A.

**Comment by bauzer714** [comment]
Mine is still working without an issue. Any chance you logged out on the browser used to populate the values? Have you repopulated the new values and still have problems?

**Comment by gboudreau** [comment]
Maybe try to remove the temp files found in the /tmp/ folder (their names start with `nest_php_`)

**Comment by ecomix** [comment]
Hi,

I don't understand what you mean with "logged out on the browser used to populate the values". I have logged months ago when I copied de issue_token and the cookie and nothing else.

In any case, I have logged again a copy one more time issue_token and the cookie, but still having the same issue.

Thanks

**Comment by ecomix** [comment]
Thanks gboudreau, it works like a charm.

**Comment by gboudreau** [comment]
This issue should be resolved by 8c2dd5c1119d2079d252240f0e3913897400e305
(published on composer as v1.2.4)
