### ISSUE TITLE
pass variable as parameter

### ISSUE THREAD

**Issue by vjooris** [gboudreau/nest-api#113]
Hello,
I'm developing a php based on your class. (this class is GREAT)
I would like to pass variable
$setTmp = 20.5 (this variable contains the target temperature  I want to set.
if I enter `$success = $nest->setTargetTemperature($setTmp);`, into my php code, I've a "nice" 500 error.
but with `$success = $nest->setTargetTemperature(20.5);` it works perfectly.

Is it possible to pass a variable ?
Thank you

**Comment by bauzer714** [comment]
Do a var_dump() on your variable. I'm betting it's not what you think it is.

**Comment by vjooris** [comment]
Hello,
Thank you for your VERY FAST response.
this is the result of the var_dump()
`string(4) "21.5" `

Sinds I'm NOT a developper, if you can telle me with I've to code for this ....

**Comment by bauzer714** [comment]
Can you paste your code?

**Comment by kueblc** [comment]
You will need to convert that string to a number

**Comment by vjooris** [comment]
yes, this is what I expected, but do you know (I didn't found it on Google) the function to convert text to number ?

**Comment by kueblc** [comment]
Try
```php
$success = $nest->setTargetTemperature((float) $setTmp)
```

This isn't really an issue with @gboudreau's nest-api, rather you might benefit from studying some PHP programming guides/tutorials.

**Comment by vjooris** [comment]
> Can you paste your code?

please. Thank you for your help, this is a RAW code...

[Nest.php.txt](https://github.com/gboudreau/nest-api/files/4210090/Nest.php.txt)

**Comment by vjooris** [comment]
> Try
> 
> ```
> $success = $nest->setTargetTemperature((float) $setTmp)
> ```
> 
> This isn't really an issue with @gboudreau's nest-api, rather you might benefit from studying some PHP programming guides/tutorials.

I'd tried `float ($setTmp)`  without success, but pour syntax works perfectly !
THANK YOU.

P.S. : of course this was not an issue, but just help needed ...

**Comment by vjooris** [comment]
P.S. : of course this was not an issue, but just help needed ...

**Comment by kueblc** [comment]
> P.S. : of course this was not an issue, but just help needed ...

This is not the place to ask for help with learning PHP. There are countless forums and resources out there to help you learn to program. Continuing to open issues on projects to ask for help with unrelated problems is an abuse of maintainer time. Please stop and do some basic research.

**Comment by vjooris** [comment]
ok, I'm do not want to abuse anyone. 
I thought here was the best place to ask a specific question on the development.
I already searched on Google without success....
I'll stop asking questions.
Anyway, thank you for your help
