### ISSUE TITLE
time_to_target

### ISSUE THREAD

**Issue by vjooris** [gboudreau/nest-api#114]
N.B. : this is not an issue, but a question

Hi, 
I keep having some questions, as I'm not a developper, so I need help ...

on my Android tel, when I see (for exile) :  more than 2 hours in 2+ hr)
time_to_target returns a very big number (1582399960).
Wat is the unit of this ? How to get an answer in a format h:mm
This my "code":
`	echo "<i>Time to target temperature : </i>".$infos->target->time_to_target."<br>";
`
Thank you for your help

**Comment by bauzer714** [comment]
It's the Unix timestamp. 

https://www.unixtimestamp.com/index.php

**Comment by vjooris** [comment]
OK, I though we get a duration to targe température, but we receive a date & time when target tmp will be ok.
So for the duration, I've to substrat this result with now()

**Comment by bauzer714** [comment]
You now understand the data response. You can use Google searches to achieve your goal.

**Comment by bauzer714** [comment]
@gboudreau please close this. Not an issue.
