### ISSUE TITLE
couldn't find issueToken

### ISSUE THREAD

**Issue by jluc2808** [gboudreau/nest-api#117]
hello, i follow the instruction to find issue_Token to set in php program
what i get is 
<iframe id="ssIFrame_google" sandbox="allow-scripts allow-same-origin" aria-hidden="true" frame-border="0" style="position: absolute; width: 1px; height: 1px; left: -9999px; top: -9999px; right: -9999px; bottom: -9999px; display: none;" src="https://accounts.google.com/o/oauth2/iframe#origin=https%3A%2F%2Fhome.nest.com&amp;rpcToken=xxxxxxxxxx&amp;clearCache=1"></iframe>

which doesn't seem to be the exact code expected under the $issueToken value 
Inside dev tools i could access to the storage > Cookies which have 2 entries 
https://home.nest.com
https;//accounts.google.com
or under local storage the same entries 

could you give instruction about the field to store under $issueToken and $Cookies 

thanks 
jluc

**Comment by vjooris** [comment]
I'm not sure to properly understand your question, because I followed the same instructions without problem. (with Google account, not the Nest account).
Did you used Google Chrome ?

**Comment by jluc2808** [comment]
yes i'm using the google account to connect the Nest.com

**Comment by vjooris** [comment]
OK, and for the second question  ?

**Comment by gboudreau** [comment]
@jluc2808 Read the instructions carefully. The values you need are from the Network tab, not Storage > Cookies. One is a URL that will appear at the top, when you select a request in the list of the Network tab, the other will be the Cookies value that appears lower, again when you select the appropriate request in the list. Which requests to select is detailed in the instructions.

**Comment by jluc2808** [comment]
sorry, it's the 1st time i'm using this part of the dev, now it's OK i found the value. 
thanks a lot 
jluc2808
