### ISSUE TITLE
update to use Google Nest Device Access program

### ISSUE THREAD

**Issue by frankenbubble** [gboudreau/nest-api#133]
Hi,

Google have finally setup the new API to access nest, although you have to pay $5 to register as a dev.  Its a little less functional than this code, no hotwater support for example.

Do you have thoughts/plans to integrate so auth is reliable ?

https://console.nest.google.com/device-access/tos  and docs  https://developers.google.com/nest/device-access/traits

**Comment by gboudreau** [comment]
No intentions to look into this myself at this time. But I', open to review any PR I would receive to integrate this.
Thanks for the links.

**Comment by bauzer714** [comment]
I'm not sure this class would be a good fit as the capabilities are not near to equivalent with a nontrivial number missing. It looks like one would better off creating a new library all together and then creating a middleware or strategy pattern to allow people to transition without significant work.

**Comment by frankenbubble** [comment]
I agree, I did some playing with it last night, and it's way to limited or my use case.  for example, doesn't support hotwater , doesn't give details on frost settings .... which are things i use in this class to graph stuff.  It's quite disappointing, maybe it will get better.

i've a nest hello, and it's nice there is event support for that, maybe someone will connect that to alexa to announce users, but even some of those docs are weird, like announcing a user, it gives a user id, not a friendly name
