### ISSUE TITLE
Issue getting Nest Info

### ISSUE THREAD

**Issue by chadderwick** [gboudreau/nest-api#136]
Started getting errors on 2/11.

This is the first error:
Notice: Undefined offset: 0 in /nest.class.php on line 999

seems like it can no longer connect to the nest...anybody else getting this issue?

**Comment by knappster1** [comment]
Yes.  See:
https://github.com/gboudreau/nest-api/issues/135
And
https://github.com/gboudreau/nest-api/issues/115#issuecomment-596142188

**Comment by chadderwick** [comment]
ahh...apologies. I thought it was a new issue so didn't get that far down in the comments.

This fixed by issue...thank you!!!
