### ISSUE TITLE
Script stopped working at 09:47 this morning. Had been working great for weeks.

### ISSUE THREAD

**Issue by thadmccall** [gboudreau/nest-api#137]
Hi, I had this working perfectly for a couple of week and now it has stopped working.

I had set this up using a google account as I unfortunately migrated from my Nest account.

I am getting these errors:

```
PHP Notice:  Undefined offset: 0 in /opt/splunk/admin/bin/nest.class.php on line 999
PHP Notice:  Undefined property: stdClass::$link in /opt/splunk/admin/bin/nest.class.php on line 373
PHP Notice:  Trying to get property of non-object in /opt/splunk/admin/bin/nest.class.php on line 373
PHP Notice:  Trying to get property of non-object in /opt/splunk/admin/bin/nest.class.php on line 373
PHP Notice:  Undefined offset: 1 in /opt/splunk/admin/bin/nest.class.php on line 373
PHP Fatal error:  Cannot access empty property in /opt/splunk/admin/bin/nest.class.php on line 374
```

I went through the process of getting my auth URL and cookie again several times thinking that might have changed but I still can't get it to work.

**Comment by zecanard** [comment]
I wonder what’s happening at Google that we’re getting more of these all of a sudden:
#136
https://github.com/gboudreau/nest-api/issues/135#issuecomment-776344673
https://github.com/gboudreau/nest-api/issues/115#issuecomment-596142188

**Comment by thadmccall** [comment]
So I got it working. Deleted the thermostat from the Android app. Then on the thermostat went to Settings, Reset, WWN Connection. Set up the WIFI connection and added the thermostat back to the app. I'm pulling data again from this script.
