### ISSUE TITLE
Support for multiple thermostats

### ISSUE THREAD

**Issue by bwhiteford** [gboudreau/nest-api#41]
Hello and thanks for putting together this excellent PHP interface. I am using it in my home with one of the thermostats, but can't seem to figure out how to make it talk to both thermostats on my account. Could you share how I might go about doing that?

Thank you!

**Comment by jase31** [comment]
Can anyone give any more info how to specify which thermostat to read the data from. I have the MattHirschfelt/Nest-Extended script to collect data using the gboudreau api. however it is reading only from the first nest. How can I read the data from the second nest? Can anyone give a bit of a pointer -

**Comment by gboudreau** [comment]
My API needs the Nest device serial to be sent in parameter of all function calls, if you don't want to use the 1st device.
In Next-Extended, those function calls are made in `resources/utils/nest-get-data.php`:
https://github.com/MattHirschfelt/Nest-Extended/blob/master/resources/utils/nest-get-data.php#L38
and
https://github.com/MattHirschfelt/Nest-Extended/blob/master/resources/utils/nest-get-data.php#L74

So at the top of that script (at line 21 for example), you could add: `$devices_serials = $nest->getDevices();`
And then change the two lines above (L38 and L74) to use the serial number you want:
`$infos = $nest->getDeviceInfo($devices_serials[1]);`
`$energy = $nest->getEnergyLatest($devices_serials[1]);`
