### ISSUE TITLE
API is failing to get device data?

### ISSUE THREAD

**Issue by 75nineteen** [gboudreau/nest-api#42]
Warning: Invalid argument supplied for foreach() in /../resources/libs/nest/nest.class.php on line 510

Warning: Invalid argument supplied for foreach() in /../resources/libs/nest/nest.class.php on line 502

https://github.com/gboudreau/nest-api/blob/master/nest.class.php#L508-L526

**Comment by gboudreau** [comment]
You're not using the latest version of the class, or you modified it, because lines 502 and 510 are not `foreach()` commands.
Try using the latest, and use the example.php script to test it. Just add a `die()` on L26: https://github.com/gboudreau/nest-api/blob/master/examples.php#L26

**Comment by 75nineteen** [comment]
@gboudreau Ok. Thanks.
