### ISSUE TITLE
Having Issues and I am Baffled

### ISSUE THREAD

**Issue by rossking** [gboudreau/nest-api#44]
Fatal error: Uncaught exception 'RuntimeException' with message 'Error: HTTP request to https://home.nest.com/user/login returned an error: couldn't connect to host' in /var/homeauto/Classes/nest.class.php:705
Stack trace:
#0 /var/homeauto/Classes/nest.class.php(637): Nest->doRequest('POST', 'https://home.ne...', Array)
#1 /var/homeauto/Classes/nest.class.php(588): Nest->doPOST('https://home.ne...', Array)
#2 /var/homeauto/Classes/nest.class.php(99): Nest->login()
#3 /var/homeauto/Module/NEST_PULL.php(55): Nest->__construct('Email@onebx...', 'Password')
#4 /var/homeauto/HomeAutoFeed.php(161): NEST_PULL()
#5 {main}
  thrown in /var/homeauto/Classes/nest.class.php on line 705

I have checked curl and it is active

Not sure what elese to check

**Comment by gboudreau** [comment]
Try on the command line:
`curl https://home.nest.com/user/login`
Response should be:
`provide authorization`

**Comment by rossking** [comment]
Yes works fine

**Comment by gboudreau** [comment]
Line 637 in nest.class.php doesn't match your error. Are you sure you're using the latest version?
https://github.com/gboudreau/nest-api/blob/master/nest.class.php#L637

**Comment by gboudreau** [comment]
Also look for a cacert.pem file in your temp folder (/tmp).
My class should create it, if it doesn't exist, is too old, or has a small size (< 100kB), but that last check was added recently, so maybe the old version of the class you're using isn't checking for that, and you have an invalid cacert.pem file. Latest version of the class will fix that, or just rm that file to have it re-created.

**Comment by rossking** [comment]
Fatal error:  Uncaught exception 'RuntimeException' with message 'Error: HTTP request to https://home.nest.com/user/login returned an error: couldn't connect to host' in /var/homeauto/www/Classes/nest.class.php:701
Stack trace:
#0 /var/homeauto/www/Classes/nest.class.php(633): Nest->doRequest('POST', 'https://home.ne...', Array)
#1 /var/homeauto/www/Classes/nest.class.php(584): Nest->doPOST('https://home.ne...', Array)
#2 /var/homeauto/www/Classes/nest.class.php(99): Nest->login()
#3 /var/homeauto/www/TEST.php(20): Nest->__construct('email...', 'pass')
#4 {main}
  thrown in /var/homeauto/www/Classes/nest.class.php on line 701

**Comment by rossking** [comment]
I blew out all old code and replaced and re ran, lines moved a bit but same error

**Comment by rossking** [comment]
brand new server never worked

I saw the cem file before, but now I don't just a cach and cookie file

**Comment by gboudreau** [comment]
You have DEBUG defined as FALSE, right?
Having it set to TRUE will try to connect to a proxy at 127.0.0.1:8888, which you don't have.

**Comment by gboudreau** [comment]
Also to try on command line:
`php -r 'echo file_get_contents("https://home.nest.com/user/login");'`

**Comment by rossking** [comment]
Thanks

I had other issues so I turned on hoping they would display themselves

I have a debug that just throws out errors and doesn't hide them

Your debug is not documented so I made assumption, Turning that back to False solved this issue

Might want to add note to not touch as it is for internal debug only.

**Comment by rossking** [comment]
Thanks for the great Class it has worked excellent over the years on another PI, But I upgraded for more horsepower on the DB and then it stopped working

**Comment by rossking** [comment]
now I get the original error I was trying to debug

file_put_contents(/tmp/nest_php_cache_09255254939caa89971804d1bd030996): failed to open stream: Permission denied in /var/homeauto/www/Classes/nest.class.php on line 625

**Comment by rossking** [comment]
OK Problem Solved

I had issue and turned on Debug, I fixed issue but new issue became the debug being left ON

My test function referenced 1 copy and my production referenced another copy of the class so as I made changes to debug only one of them were being changed.

I turned off debug and problem is gone Global

Thanks for your Help
