### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tobiaskluge** [gboudreau/nest-api#55]
Hello,

What is the license of this project? It would be great if you could add a short paragraph or LICENSE file to your project.

Greetings and thanks for your effort!
Tobias

**Comment by gboudreau** [comment]
Will add a license file later today. License is GPLv3.

**Comment by tobiaskluge** [comment]
Hey Guillaume,

Thanks a lot! Any change to change it to a more commercial-friendly license as e.g. MIT?

Greetings,
Tobias

**Comment by gboudreau** [comment]
Sorry, but no. GPLv3 was chosen expressly to prevent commercial use.
Even if I allowed it, Nest do not allow this kind of access to their private APIs. They have a developper program, and that is the only legal point of entry for interfacing with Nest products.
