### ISSUE TITLE
Nest returns empty response

### ISSUE THREAD

**Issue by pmcanseco** [gboudreau/nest-api#57]
So I was able to get this class working just fine, but I think I may have made too many requests or something because now I'm getting an empty response. This wouldn't be an issue with this class, right? Does anyone know the API request limits?

`Fatal error: Uncaught exception 'RuntimeException' with message 'Error: Received empty response from request to https://czfe04-front01-iad01.transport.home.nest.com/v3/mobile/user.xxxxxx.' in /var/www/nest.class.php:732 Stack trace: #0 /var/www/nest.class.php(655): Nest->doRequest('GET', '/v3/mobile/user...') #1 /var/www/nest.class.php(487): Nest->doGET('/v3/mobile/user...') #2 /var/www/nest.class.php(207): Nest->getStatus() #3 /var/www/nest.php(12): Nest->getDeviceInfo() #4 {main} thrown in /var/www/nest.class.php on line 732`

**Comment by nadams5755** [comment]
visiting https://home.nest.com returns a 500 as well.

**Comment by Pirate43** [comment]
glad it's not just me. Their service status page says there's some intermittent issues they are aware of but it's dated September 8th.

**Comment by MikeKemmerer** [comment]
I'm getting the same exception.

On Sunday, September 13, 2015, Pablo Canseco <notifications@github.com>
wrote:

> glad it's not just me. Their service status page says there's some
> intermittent issues they are aware of but it's dated September 8th.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gboudreau/nest-api/issues/57#issuecomment-139913271>.
>


-- 
------------------------------
Michael Kemmerer

**Comment by gboudreau** [comment]
I stopped receiving exceptions.
Happens from time to time for me, with one error or another. Always fixes itself in minutes/hours.
