### ISSUE TITLE
Nest Protect - examples.php need an update

### ISSUE THREAD

**Issue by tonyrsutton** [gboudreau/nest-api#64]
Is anyone able to update the examples.php file to include the Nest Protect features as there are currently none in there (apart from device/serial)? I'm having a hard time trying to understand the structure to allow me to output the results from it.

@bauzer714 thank you for adding the v2 features to it, it looks like a good list!

Thanks

**Comment by bauzer714** [comment]
What features specifically? I have the latest protect and thermostat and get everything?

**Comment by bauzer714** [comment]
Okay.I didn't read you wanted examples updated. What you looking for that's not there? Been awhile since I've looked at it.

**Comment by tonyrsutton** [comment]
Thanks for the response. I'll give you a quick example...

If I wanted the latest temperature, I use this line...

`printf("The temperature is currently at %.02f%s\n", $infos->current_state->temperature, $infos->scale);`

which outputs the figures.

But with the Protect, it's either coming out as blank or 0 and I can't figure out what I am doing wrong.

**Comment by bauzer714** [comment]
Well to start. Your protects don't report temperatures.

**Comment by tonyrsutton** [comment]
Obviously, the above code was an example. :P It's pretty much of the functions like co_status, smoke_status and so on. I was excepting for a string to be returned, but I got nothing.

Hence for the exampes.php to be updated so I can see what I am missing.

**Comment by gboudreau** [comment]
```php
$infos = $nest->getDeviceInfo($protect_serial);
var_dump($infos);
var_dump($infos->co_status);
```
```php
object(stdClass)#127 (24) {
  ["co_status"]=>
  string(2) "OK"
  ["co_previous_peak"]=>
  NULL
  ["co_sequence_number"]=>
  int(1)
  ["smoke_status"]=>
  string(2) "OK"
  ["smoke_sequence_number"]=>
  int(1)
  ["model"]=>
  string(10) "Topaz-1.11"
  ["software_version"]=>
  string(6) "2.0rc5"
  ["line_power_present"]=>
  bool(true)
  ["battery_level"]=>
  int(5304)
  ["battery_health_state"]=>
  string(2) "OK"
  ["wired_or_battery"]=>
  int(0)
  ["born_on_date"]=>
  string(10) "2014-05-28"
  ["replace_by_date"]=>
  string(10) "2021-05-28"
  ["last_update"]=>
  string(19) "2016-04-29 17:46:03"
  ["last_manual_test"]=>
  string(19) "2016-01-16 09:08:56"
  ["ntp_green_led_brightness"]=>
  int(3)
  ["tests_passed"]=>
  array(12) {
    ["led"]=>
    bool(true)
    ["pir"]=>
    bool(true)
    ["temp"]=>
    bool(true)
    ["smoke"]=>
    bool(true)
    ["heat"]=>
    bool(true)
    ["wifi"]=>
    bool(true)
    ["als"]=>
    bool(true)
    ["co"]=>
    bool(true)
    ["us"]=>
    bool(true)
    ["hum"]=>
    bool(true)
    ["speaker"]=>
    NULL
    ["buzzer"]=>
    NULL
  }
  ["nest_features"]=>
  array(7) {
    ["night_time_promise"]=>
    bool(true)
    ["night_light"]=>
    bool(true)
    ["auto_away"]=>
    bool(true)
    ["heads_up"]=>
    bool(true)
    ["steam_detection"]=>
    bool(true)
    ["home_alarm_link"]=>
    int(0)
    ["wired_led_enable"]=>
    bool(true)
  }
  ["serial_number"]=>
  string(16) "05CA02AC081401AA"
  ["location"]=>
  string(36) "101356f0-af21-11e1-9ebb-1231391e8b17"
  ["network"]=>
  object(stdClass)#4 (3) {
    ["online"]=>
    bool(true)
    ["local_ip"]=>
    string(15) "192.168.155.201"
    ["mac_address"]=>
    string(12) "18b430233eea"
  }
  ["name"]=>
  string(2) "2e"
  ["where"]=>
  string(8) "Upstairs"
  ["color"]=>
  string(5) "white"
}
```
```php
string(2) "OK"
```

**Comment by tonyrsutton** [comment]
Thanks for that. While yours returned useful results, mine returned the result from my Nest Thermostat and not from my 2 x Protects, which is very interesting. It also did not list all of these Protect status, just from the Nest Thermostat.

Something is odd going on and your code is similar to what I had, so will investigate further to why this is returning wrong info...

**Comment by gboudreau** [comment]
You are probably not giving the correct serial number to `getInfos()`. You can list all you devices serial numbers using:
```php
$devices_serials = $nest->getDevices();
var_dump($devices_serials);
```

**Comment by tonyrsutton** [comment]
Turns out you're right, my code is not passing on the serial number to it for some reasons. When I hardcoded the serial number to getDeviceInfo, it worked and got the result I needed. So that's my starting point to look at it and go from there.

Thank you ever so much for your help, it gives me better understanding of how Nest API are structured.
