### ISSUE TITLE
Extremely slow to get data

### ISSUE THREAD

**Issue by webpirate** [gboudreau/nest-api#65]
Has anyone had any troubles getting the data with nest.class.php?
Its now taking > 4 minutes to get the data.
Tried 2 different hosting accounts and same result.....

**Comment by gboudreau** [comment]
Indeed, it seems very slow. What was taking a few seconds at most before (`$nest->getDeviceInfo()`) is now taking 45s.
If it doesn't resolve itself in a few days, and the Nest mobile app behaves as expected, please poke me again; I'll have a look, see if I can find a way to work around this.
This class uses an old version of the API; maybe we'll need to update it to use the latest, which is probably better maintained and monitored.

**Comment by webpirate** [comment]
Same problem. 3-4 minutes to get data. It all comes in(I think) but takes for ever.

**Comment by traveler2100** [comment]
Same problem here, 2 to 3 minutes to read or write. Some writes timing out. Thanks for the work on this, my ISY HA system uses it everyday.

**Comment by gboudreau** [comment]
I found the problem: Nest have implemented throttling; if you make a second API call within 20 seconds of the first one, you response will be throttled by X seconds:
- two API calls within 5 seconds: second API call will take 15 seconds to return the response;
- two API calls within 10 seconds, second API call will take 10 seconds to return the response;
- two API calls within the same second, second API call will take 20 seconds to return the response.

So, to prevent delays, we need to ensure that we don't call the API more than once per 20 seconds.
The issue with that, with the current code, is that the `getStatus()` API gets called every time you call any of the `getXYZ()` method.
I will change that to ensure `getStatus()` is only called once, at the beginning of the script.
If you have a script that is running for a long time, you will want to call `clearStatusCache()`, but not more often than once every 20 seconds.

Also note that poking your Nest more than once every 10 minutes will slowly deplete its battery, which will force your thermostat to disconnect from WiFi once in a while.

**Comment by webpirate** [comment]
YOU ARE A LIFE SAVER!! Class works perfect and I think faster than before... Thanks so much for your help!!

**Comment by lypkkcat** [comment]
I have the same problem. Using the updated class solves the problem.
