### ISSUE TITLE
Failed opening required '/var/www/html/nest.php'

### ISSUE THREAD

**Issue by Placid7** [gboudreau/nest-api#66]
I understand this is not really the correct place for this query, but hey why not?

I keep returning Failed opening required '/var/www/html/nest.php'. The nest.class.php is in the /var/www/html/ dir.

I'm a little stumped as my nest.php is set like your example:
// The Nest API Class file
require_once('nest.class.php');

My loaded php.ini has:
; UNIX: "/path1:/path2"
include_path = ".:/usr/share/php:/var/www/html"

Is there a change I need to make in my loaded php.ini?

**Comment by gboudreau** [comment]
> Failed opening required '/var/www/html/nest.php'
> The nest.class.php is in the /var/www/html/ dir.

nest.php vs nest.class.php
i.e. the error you pasted is not about nest.class.php, but nest.php, and the failure to open that file.
Check where it is saved, how it is 'required', and its permissions/ownership.

**Comment by Placid7** [comment]
It was actually an error with the API I was using. Trashed the old one and copied your's and is working fine.

Now on to try and get a mysql database running. I appreciate the quick response.
