### ISSUE TITLE
Can the API be called from a Bash script instead of php?

### ISSUE THREAD

**Issue by rr0ss0rr** [gboudreau/nest-api#67]
Hi .. I'm not a Web/PHP/Python guy but am pretty good at Unix Bash scripts .. Any way to call the API from a Unix Bash script?  I just need to retrieve info from the Thermostat and update the humidity level based on outside temperature.

Thanks

**Comment by gboudreau** [comment]
You will need PHP-cli installed, but with that, it's quite easy to create a script that just outputs the current humidity level:

```php
#!/bin/env php
<?php
require_once('nest.class.php');
define('USERNAME', 'you@gmail.com');
define('PASSWORD', 'Something other than 1234 right?');
$nest = new Nest();
$infos = $nest->getDeviceInfo();
echo $infos->current_state->humidity;
```

Make the file executable, and make sure `nest.class.php` is in your PHP include folder.

To find which folders you can put `nest.class.php` into, use this:
```bash
gb@server:~ $ php -i | grep -i include_path
include_path => .:/usr/share/pear:/usr/share/php => .:/usr/share/pear:/usr/share/php
```
In the above case, I can either have it in the current folder (the folder I'm in, when executing the script, which is not necessarily the same as the folder where the script is), or /usr/share/php/nest.class.php, or /usr/share/pear/nest.class.php.

**Comment by rr0ss0rr** [comment]
Thanks .. I'll play around with this .. A few questions

$infos variable would have all the current settings from the nest?
Can you explain the echo below it?  
Once I decide what the humidity level should be, how would I send that to the nest?

Thanks again
