### ISSUE TITLE
Eco Mode Code updates

### ISSUE THREAD

**Issue by cleomagic** [gboudreau/nest-api#76]
I'm glad I found this tool as it allows me to fix the recently broken manual away mode. (Thanks Google). I did find some issues with code setting Eco Mode.  As written, it only sets it for the primary Thermostat, even when a different thermostat is commanded.

In the function setAway the following lines should be updated as follows to pass the $serial_number:
```
if ($away == AWAY_MODE_ON) {
   $this->setEcoMode(ECO_MODE_MANUAL, $serial_number); 
} else {
    $this->setEcoMode(ECO_MODE_SCHEDULE, $serial_number);
}

```
Additionally, Eco Mode status should be returned in the function getDeviceInfo by adding the following: to the list structure and the "$infos->current state" object
```
$ecomode = $this->last_status->device->{$serial_number}->eco->mode;	//manual-eco, auto-eco, schedule
...
'eco_mode' => $ecomode,
```
Thanks again for a great tool

**Comment by gboudreau** [comment]
There you go. Thanks for the pointers.
