### ISSUE TITLE
ON / OFF function

### ISSUE THREAD

**Issue by team18fr** [gboudreau/nest-api#78]
Hi and thank you for your work. I try to turn on the themostat nest when it is OFF, I arrive very well to extinguish it but I do not see what function to turn it on.

**Comment by gboudreau** [comment]
To turn it on, you need to use `setTargetTemperatureMode()`
Ref: https://github.com/gboudreau/nest-api/blob/master/nest.class.php#L457

Examples:
```
$nest->setTargetTemperatureMode(TARGET_TEMP_MODE_HEAT, 80);
$nest->setTargetTemperatureMode(TARGET_TEMP_MODE_COOL, 70);
$nest->setTargetTemperatureMode(TARGET_TEMP_MODE_RANGE, [72,78]);
```

**Comment by team18fr** [comment]
Thanks but if I want to have the old temperature?

**Comment by gboudreau** [comment]
You'll need to remember it from the previous value of 
`$nest->getDeviceInfo()->target->temperature`, or you can modify the `setTargetTemperatureMode()` method to not require a `$temperature`:

```diff
        $serial_number = $this->getDefaultSerial($serial_number);

+        if ($temperature !== NULL) {
                if ($mode == TARGET_TEMP_MODE_RANGE) {
                    [...]
                } elseif ($mode != TARGET_TEMP_MODE_OFF) {
                    [...]
                }
+        }

        $data = json_encode(array('target_change_pending' => TRUE, 'target_temperature_type' => $mode));
        return $this->doPOST("/v2/put/shared." . $serial_number, $data);

**Comment by team18fr** [comment]
Thank you but on my php file I have to put in how because it returns me a mistake?
 `$nest_api->setTargetTemperatureMode(TARGET_TEMP_MODE_COOL, 19 , $eqLogic->getLogicalId());`

**Comment by team18fr** [comment]
I succeeded in putting a value but after the modification as you marked me at the top I always a message asking me a value?

**Comment by team18fr** [comment]
Thank you it works great.
