### ISSUE TITLE
auto_away

### ISSUE THREAD

**Issue by team18fr** [gboudreau/nest-api#79]
Hello I come back to you for a problem:
Auto away = motion detector status how to enable or disable it
SetAutoAwayEnabled = enable / disable eco-temperature when you are away, but how to see the status.

Thank you

**Comment by team18fr** [comment]
Hi it is possible to disable motion detection?

**Comment by bauzer714** [comment]
Do you mean enable/disable auto away?  I haven't tested it, but I think calling setAutoAwayEnabled with true/false should do this.
-Brice

**Comment by team18fr** [comment]
No it is not the same thing:
SetAutoAwayEnabled allows to activate / deactivate: To automatically use the temperatures eco
and
Auto_away gives the status of the motion detector.

**Comment by bauzer714** [comment]
Okay so what is it you're trying to do? You need to give a better description of what you want.

**Comment by team18fr** [comment]
I want to be able to activate / deactivate motion detection if possible, which corresponds to Auto_Away

**Comment by gboudreau** [comment]
There is no way to disable only the motion detection.

But you can disable Nest Sense Auto-Away with `setAutoAwayEnabled()`:
> Enable or disable Nest Sense Auto-Away.

This will effectively disable the feature that automatically puts your Nest in away mode when there is no presence detected. It includes the motion sensor, but also the position of your cell phones, if you configured that.

**Comment by team18fr** [comment]
Thank you but I do not understand too much because `set AutoAway Enabled `()` just disable the eco-temperature when the house is unoccupied and the motion detector remains enabled?

**Comment by gboudreau** [comment]
That method changes the `auto_away_enable` value on the Nest API.
That flag indeed seems to be used by the "Use ECO temperatures when you're away from home" feature.
The Nest Sense Auto-Away functionality is gone from the web app, so unless you can find what you want there, there is no way change that using the Nest API.

**Comment by gboudreau** [comment]
I renamed the method in the latest version of the class to reflect this change in the Nest API.
