### ISSUE TITLE
Function getDeviceInfo

### ISSUE THREAD

**Issue by team18fr** [gboudreau/nest-api#80]
Hi I would like to know how to have only one info like for example last_connection.
thank you

**Comment by bauzer714** [comment]
I think the examples handle this exact scenario, but this should work. 

<?php
require('nest.class.php');

$username = 'you@gmail.com';
$password = 'Something other than 1234 right?';
$nest = new Nest($username,$password);
$infos = $nest->getDeviceInfo();
echo $infos->network->last_connection;
?>

**Comment by team18fr** [comment]
Thank you that is what I was looking for
