### ISSUE TITLE
Alarm nest protect

### ISSUE THREAD

**Issue by team18fr** [gboudreau/nest-api#81]
Hello I would like to know if it is possible to disengage the alarm from the nest protect.

**Comment by bauzer714** [comment]
Disable the core functionality of the device, no. This is not possible.

**Comment by team18fr** [comment]
No I would like to make it sounded

**Comment by bauzer714** [comment]
Not possible at the time, no. I highly doubt they would expose that functionality.

**Comment by team18fr** [comment]
Thank you
