### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function curl_ init() in X:\nest.class.php:1053

### ISSUE THREAD

**Issue by jocamero** [gboudreau/nest-api#82]
Hello, updated to the latest version of the nest-api and PHP and I'm now getting the following error.  Was working prior to the upgrade for many years.  Any help would be appreciated.

---

X:\>php NightFan.php
PHP Fatal error:  Uncaught Error: Call to undefined function curl_
init() in X:\nest.class.php:1053
Stack trace:
#0 X:\nest.class.php(1037): Nest->doRequest('POST', 'https://home.ne...', Array)

#1 X:\nest.class.php(968): Nest->doPOST('https://home.ne...', Array)
#2 X:\nest.class.php(121): Nest->login()
#3 X:\NightFan.php(21): Nest->__construct()
#4 {main}
  thrown in X:\nest.class.php on line 1053

---

code:

```
<?php

error_reporting(E_ALL);

require_once('nest.class.php');

// Your Nest username and password.
define('USERNAME', 'xxxxxxxxxxxxxxx');
define('PASSWORD', 'xxxxxxxxxxxxxxx');

date_default_timezone_set('America/Denver');

$nest = new Nest();

echo "Setting fan mode...\n";
$success = $nest->setFanMode(FAN_MODE_ON); // Available: FAN_MODE_AUTO or FAN_MODE_EVERY_DAY_OFF, FAN_MODE_ON or FAN_MODE_EVERY_DAY_ON
// setFanMode() can also take an array as it's argument. See the comments below for examples (FAN_MODE_TIMER, FAN_MODE_MINUTES_PER_HOUR).
var_dump($success);
```

**Comment by gboudreau** [comment]
You are missing the cURL PHP extension. Simply install or enable it, and it should work fine then.

**Comment by jocamero** [comment]
gboudreau Thanks so much for the quick help!  Sorry to bother!
