### ISSUE TITLE
Turn off

### ISSUE THREAD

**Issue by team18fr** [gboudreau/nest-api#84]
Hi when I put the thermostat in OFF mode no temperature is sent how to make it sends 0 °. Thank you

**Comment by gboudreau** [comment]
Why would you want to send 0˚?
I'm pretty sure you can't set a thermostat to 0˚, using my class or otherwise.

My class only allows you to do, in PHP, what you can do using the mobile or web apps.

**Comment by team18fr** [comment]
I use the jQuery-Knob slider and it does not reset to 0 when no temperature is sent to it.

**Comment by gboudreau** [comment]
Definitely not something that the nest-api class should handle. Maybe post your code, and someone could help you with that.

**Comment by team18fr** [comment]
Ok I'll look that way. Thank you

**Comment by bauzer714** [comment]
Something that I've done that you can look into is extending the class so you can have the functions return what you want without losing the ability to update the base nest.class.php file when it is.

http://php.net/manual/it/keyword.extends.php

**Comment by team18fr** [comment]
Thank you for your help so here is what I put to test but my temperature remains empty.

`class jeedom extends Nest
{
	public function setTargetTemperatureMode($mode, $temperature = NULL, $serial_number = NULL) {
		if ($mode == TARGET_TEMP_MODE_OFF){
			$temperature = 0;
		}
	}
}`

**Comment by team18fr** [comment]
It's good I found what I wanted to do that came from other files thanks for your help.

**Comment by bauzer714** [comment]
@gboudreau please close.
