### ISSUE TITLE
Multiple Thermostats

### ISSUE THREAD

**Issue by FrdPrefct** [gboudreau/nest-api#88]
How do I use this code with multiple thermostats?
I have an upstairs and downstairs Nest.  I will also be purchasing remote thermostats that I want to retrieve data from.  Unfortunately, it's only showing one thermostat (Downstairs).

**Comment by bauzer714** [comment]
The nest will default to 1 of the thermostats. You'll need to loop through getDeviceInfo for each serial which you can get from getDevices(). Search for the them in the class to learn more.

**Comment by FrdPrefct** [comment]
Perfect, got it!  I can actually just enter the serial number and pull the info that way, instead of Looping. 
This serves my purpose!

**Comment by bauzer714** [comment]
Looping would future proof it in case of additional thermostats, RMA and replacemnt scenarios, or upgrading. But, hard coding the serial number will work as well.
