### ISSUE TITLE
Protects all Failing Heat/US tests

### ISSUE THREAD

**Issue by bauzer714** [gboudreau/nest-api#91]
Below is not really related to the library - as it's simply consuming the data provided from Nest, which is working and displaying accurate results. 

Anyone else seeing the below - for their Nest Protects?  Started coming back as false yesterday (November 1) even though Nest.com continues to show them as fine. Anyone know what these "tests" even are? 

![image](https://user-images.githubusercontent.com/370329/47943041-b5396e00-deca-11e8-880e-9d7218636c1c.png)

`tests_passed: {
led: true,
pir: true,
temp: true,
smoke: true,
heat: false,
wifi: true,
als: true,
co: true,
us: false,
hum: true,
speaker: true,
buzzer: true
},`

**Comment by gboudreau** [comment]
I get the same thing. Never checked those; do you know if we had `heat` and `us` tests to `true` before? Maybe those are for newer models of Protects, and thus are shown as `false` on the API for older models that don't support those.

**Comment by bauzer714** [comment]
They were previously true. I just use an inarray to look for false and notify me to check on them. Knowing it is affecting other people makes me feel better. I'll just suppress these for now. Perhaps you're right, but knowing Nest it could just be they broke it and QA missed it. I'll monitor over coming weeks and months.

**Comment by bauzer714** [comment]
@gboudreau - I don't know if this is new too - but it looks like the "wan_ip" address is no longer useful either. It's returning a private IP address ("172.x.x.x") and has a leading backslash.  I'm not behind a VPN or anything either, googling "what is my IP" gives me the correct IP.
