### ISSUE TITLE
No devices returned?

### ISSUE THREAD

**Issue by chrismarcellino** [gboudreau/nest-api#94]
Hi, trying to use this to adjust humidity (which cannot be done on the official API). For some reason, I get no devices. For example:

```
<?php

require_once('nest.class.php');

// Your Nest username and password.
define('USERNAME', 'xxx');
define('PASSWORD', 'xxx');

$nest = new Nest();

// Get the device information:
$infos = $nest->getDeviceInfo();
print_r($infos);
    
// Print the current temperature
printf("Current temperature: %.02f degrees %s\n", $infos->current_state->temperature, $infos->scale);
```

Gives me a bunch of nothing:
```

chrismarcellino@Chriss-MacBook-Pro nest-api-master $ php mytest.php 
stdClass Object
(
    [current_state] => stdClass Object
        (
            [mode] => off,
            [temperature] => 0
            [humidity] => 
            [ac] => 
            [heat] => 
            [alt_heat] => 
            [fan] => 
            [auto_away] => 

```
If I turn on verbose errors: 
Notice: Undefined offset: 0 in /Users/chrismarcellino/Downloads/nest-api-master/nest.class.php on line 874

Yet, the regular website/app work.  So no devices are being returned for some reason. No 2FA is on and I can log in normally. Any suggestions? Thanks!

**Comment by gboudreau** [comment]
Maybe try to check what the API is returning.
After this line: https://github.com/gboudreau/nest-api/blob/master/nest.class.php#L918
Add a new one that just output the received string, then exits: `var_export($status); die();`

**Comment by chrismarcellino** [comment]
Thanks. Here is the output. Seems like a lot of stuff but is devoid of my thermostat? Odd. I can log in with that account and see everything (1 thermostat, 2 camera, 1 doorbell and a few smoke detectors).

`
chrismarcellino@Chriss-MacBook-Pro nest-api-master $ php mytest.php 
stdClass::__set_state(array(
   'user_alert_dialog' => 
  stdClass::__set_state(array(
     '14060171' => 
    stdClass::__set_state(array(
       '$version' => -505,
       '$timestamp' => 1552751161263,
    )),
  )),
   'buckets' => 
  stdClass::__set_state(array(
     '14060171' => 
    stdClass::__set_state(array(
       '$version' => -2731,
       '$timestamp' => 1553484064644,
       'buckets' => 
      array (
        0 => 'topaz_resource.5',
        1 => 'topaz.18B4300000A6C7DD',
        2 => 'occupancy.18B4300000A6C7DD',
        3 => 'widget_track.18B4300000A6C7DD',
        4 => 'topaz_history.18B4300000A6C7DD',
        5 => 'delayed_topaz.18B4300000A6C7DD',
        6 => 'structure.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        7 => 'where.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        8 => 'utility.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        9 => 'structure_history.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        10 => 'trip.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        11 => 'wwn_security.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        12 => 'structure_metadata.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        13 => 'safety.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        14 => 'safety_summary.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        15 => 'geofence_info.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        16 => 'partner_programs.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
        17 => 'kryptonite.18B430C5B34CB113',
        18 => 'structure.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        19 => 'where.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        20 => 'utility.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        21 => 'structure_history.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        22 => 'trip.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        23 => 'wwn_security.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        24 => 'structure_metadata.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        25 => 'safety.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        26 => 'safety_summary.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        27 => 'geofence_info.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        28 => 'partner_programs.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
        29 => 'topaz.18B4300000A6EB03',
        30 => 'occupancy.18B4300000A6EB03',
        31 => 'widget_track.18B4300000A6EB03',
        32 => 'topaz_history.18B4300000A6EB03',
        33 => 'delayed_topaz.18B4300000A6EB03',
        34 => 'quartz.8729c608984442c58d9490397ba75be3',
        35 => 'quartz.810b3f2be2e84d998317aa65fc8dc4b9',
        36 => 'kryptonite.18B430CE846444A9',
        37 => 'topaz.18B43000009D7E76',
        38 => 'occupancy.18B43000009D7E76',
        39 => 'widget_track.18B43000009D7E76',
        40 => 'topaz_history.18B43000009D7E76',
        41 => 'delayed_topaz.18B43000009D7E76',
        42 => 'topaz.18B43000009E6083',
        43 => 'occupancy.18B43000009E6083',
        44 => 'widget_track.18B43000009E6083',
        45 => 'topaz_history.18B43000009E6083',
        46 => 'delayed_topaz.18B43000009E6083',
        47 => 'user.14060171',
        48 => 'user_alert_dialog.14060171',
        49 => 'message_center.14060171',
        50 => 'user_settings.14060171',
        51 => 'buckets.14060171',
        52 => 'quartz.4d707ee63ede4ada861cb4fa5990b7d5',
        53 => 'topaz.18B4300000A6D11D',
        54 => 'occupancy.18B4300000A6D11D',
        55 => 'widget_track.18B4300000A6D11D',
        56 => 'topaz_history.18B4300000A6D11D',
        57 => 'device.09AC01AC02190ZRD',
        58 => 'demand_response.09AC01AC02190ZRD',
        59 => 'device_alert_dialog.09AC01AC02190ZRD',
        60 => 'link.09AC01AC02190ZRD',
        61 => 'message.09AC01AC02190ZRD',
        62 => 'metadata.09AC01AC02190ZRD',
        63 => 'schedule.09AC01AC02190ZRD',
        64 => 'shared.09AC01AC02190ZRD',
        65 => 'hvac_partner.09AC01AC02190ZRD',
        66 => 'track.09AC01AC02190ZRD',
        67 => 'tuneups.09AC01AC02190ZRD',
        68 => 'energy_latest.09AC01AC02190ZRD',
        69 => 'energy_weekly.09AC01AC02190ZRD',
        70 => 'tou.09AC01AC02190ZRD',
        71 => 'demand_charge.09AC01AC02190ZRD',
        72 => 'demand_response_fleet.09AC01AC02190ZRD',
        73 => 'rcs_settings.09AC01AC02190ZRD',
        74 => 'cloud_algo.09AC01AC02190ZRD',
        75 => 'diagnostics.09AC01AC02190ZRD',
        76 => 'hvac_issues.09AC01AC02190ZRD',
        77 => 'delayed_topaz.18B4300000A6D11D',
      ),
    )),
  )),
   'message_center' => 
  stdClass::__set_state(array(
     '14060171' => 
    stdClass::__set_state(array(
       '$version' => -1,
       '$timestamp' => 1325379661000,
       'messages' => 
      array (
      ),
    )),
  )),
   'safety' => 
  stdClass::__set_state(array(
     '996b95d0-4802-11e9-885b-0a6ce4a9ddca' => 
    stdClass::__set_state(array(
       '$version' => -779,
       '$timestamp' => 1552751163000,
       'fd_in_progress' => false,
       'last_fd_user_identified_two_ways' => false,
       'last_fd_user_closed_doors' => false,
       'last_fd_user_tested_doors_before_entering' => false,
       'last_fd_user_stayed_low_while_exiting' => false,
       'last_fd_user_met_at_meeting_place' => false,
       'last_fd_user_took_headcount' => false,
       'last_fd_user_found_phone' => false,
       'last_manual_self_test_cancelled' => false,
       'manual_self_test_in_progress' => false,
       'audio_self_test_enabled' => false,
       'audio_self_test_notify' => false,
       'audio_self_test_repeat_interval_secs' => 0,
       'audio_self_test_force_interval_secs' => 0,
       'audio_self_test_in_progress' => false,
       'smoke_history_duration_secs' => 0,
       'co_history_duration_secs' => 0,
       'audio_self_test_participants' => 
      array (
      ),
    )),
  )),
   'utility' => 
  stdClass::__set_state(array(
     '996b95d0-4802-11e9-885b-0a6ce4a9ddca' => 
    stdClass::__set_state(array(
       '$version' => -1,
       '$timestamp' => 1,
    )),
  )),
   'where' => 
  stdClass::__set_state(array(
     '996b95d0-4802-11e9-885b-0a6ce4a9ddca' => 
    stdClass::__set_state(array(
       '$version' => 27070,
       '$timestamp' => 1552751161263,
       'wheres' => 
      array (
        0 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000004',
           'name' => 'Attic',
        )),
        1 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000001d',
           'name' => 'Back Door',
        )),
        2 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000011',
           'name' => 'Backyard',
        )),
        3 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000001',
           'name' => 'Basement',
        )),
        4 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000009',
           'name' => 'Bathroom',
        )),
        5 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000000d',
           'name' => 'Bedroom',
        )),
        6 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000017',
           'name' => 'Deck',
        )),
        7 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000003',
           'name' => 'Den',
        )),
        8 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000010',
           'name' => 'Dining Room',
        )),
        9 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000006',
           'name' => 'Downstairs',
        )),
        10 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000012',
           'name' => 'Driveway',
        )),
        11 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000000',
           'name' => 'Entryway',
        )),
        12 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000000b',
           'name' => 'Family Room',
        )),
        13 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000001b',
           'name' => 'Front Door',
        )),
        14 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000013',
           'name' => 'Front Yard',
        )),
        15 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000007',
           'name' => 'Garage',
        )),
        16 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000015',
           'name' => 'Guest House',
        )),
        17 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000001a',
           'name' => 'Guest Room',
        )),
        18 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000002',
           'name' => 'Hallway',
        )),
        19 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000008',
           'name' => 'Kids Room',
        )),
        20 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000000a',
           'name' => 'Kitchen',
        )),
        21 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000000c',
           'name' => 'Living Room',
        )),
        22 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000005',
           'name' => 'Master Bedroom',
        )),
        23 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000000e',
           'name' => 'Office',
        )),
        24 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000014',
           'name' => 'Outside',
        )),
        25 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000018',
           'name' => 'Patio',
        )),
        26 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-000100000016',
           'name' => 'Shed',
        )),
        27 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000001c',
           'name' => 'Side Door',
        )),
        28 => 
        stdClass::__set_state(array(
           'where_id' => '00000000-0000-0000-0000-00010000000f',
           'name' => 'Upstairs',
        )),
      ),
    )),
  )),
   'structure' => 
  stdClass::__set_state(array(
     '996b95d0-4802-11e9-885b-0a6ce4a9ddca' => 
    stdClass::__set_state(array(
       '$version' => 27070,
       '$timestamp' => 1552751161263,
       'away' => false,
       'name' => '',
       'creation_time' => 1552751161263,
       'topaz_hush_key' => 'Bmzz2waJWBMvPeqOchj9lw==',
       'topaz_away' => false,
       'user' => 'user.14060171',
       'devices' => 
      array (
      ),
       'swarm' => 
      array (
      ),
       'fabric_ids' => 
      array (
      ),
       'clutches' => 
      array (
      ),
       'members' => 
      array (
        0 => 
        stdClass::__set_state(array(
           'user' => 'user.14060171',
           'roles' => 
          array (
            0 => 'owner',
          ),
        )),
      ),
       'rcs_sensor_swarm' => 
      array (
      ),
    )),
  )),
   'partner_programs' => 
  stdClass::__set_state(array(
     '996b95d0-4802-11e9-885b-0a6ce4a9ddca' => 
    stdClass::__set_state(array(
       '$version' => 29571,
       '$timestamp' => 1552751162598,
    )),
  )),
   'trip' => 
  stdClass::__set_state(array(
     '996b95d0-4802-11e9-885b-0a6ce4a9ddca' => 
    stdClass::__set_state(array(
       '$version' => 30898,
       '$timestamp' => 1552751162598,
       'trips' => 
      array (
      ),
    )),
  )),
   'user' => 
  stdClass::__set_state(array(
     '14060171' => 
    stdClass::__set_state(array(
       '$version' => -29027,
       '$timestamp' => 1553574065889,
       'name' => 'homephone@levelview.com',
       'short_name' => 'Home Automation',
       'acknowledged_onboarding_screens' => 
      array (
        0 => 'rcs',
      ),
       'email' => 'homephone@levelview.com',
       'invite_accepted_timestamp' => 1552751943360,
       'structures' => 
      array (
        0 => 'structure.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
      ),
       'structure_memberships' => 
      array (
        0 => 
        stdClass::__set_state(array(
           'structure' => 'structure.d87f21a0-ad1e-11e1-9ebb-1231391e8b17',
           'roles' => 
          array (
            0 => 'member',
          ),
        )),
        1 => 
        stdClass::__set_state(array(
           'structure' => 'structure.996b95d0-4802-11e9-885b-0a6ce4a9ddca',
           'roles' => 
          array (
            0 => 'owner',
          ),
        )),
      ),
       'is_merged_with_gaia' => false,
    )),
  )),
   'geofence_info' => 
  stdClass::__set_state(array(
     '996b95d0-4802-11e9-885b-0a6ce4a9ddca' => 
    stdClass::__set_state(array(
       '$version' => -26070,
       '$timestamp' => 1552751162598,
       'fences' => 
      array (
      ),
       'device_events' => 
      array (
      ),
    )),
  )),
   'user_settings' => 
  stdClass::__set_state(array(
     '14060171' => 
    stdClass::__set_state(array(
       '$version' => -17282,
       '$timestamp' => 1552751271404,
       'email_verified' => true,
       'tos_accepted_version' => 1527058800000,
       'receive_marketing_emails' => false,
       'receive_nest_emails' => false,
       'receive_support_emails' => true,
       'max_structures' => 3,
       'max_thermostats' => 60,
       'max_thermostats_per_structure' => 20,
       'max_smoke_detectors_per_structure' => 18,
       'max_smoke_detectors' => 54,
       'max_wwn_devices_per_structure' => 10,
       'max_wwn_devices' => 20,
       'max_kryptonites' => 54,
       'max_kryptonites_per_structure' => 18,
       'max_kryptonites_per_thermostat' => 6,
       'tos_minimum_version' => 1527058800000,
       'tos_current_version' => 1527058800000,
       'app_swu_minimum_version' => 
      stdClass::__set_state(array(
         'pairing' => 2,
      )),
       'lang' => 'en_US',
       'has_location_history' => false,
       'state_2fa' => 'none',
    )),
  )),
   'structure_metadata' => 
  stdClass::__set_state(array(
     '996b95d0-4802-11e9-885b-0a6ce4a9ddca' => 
    stdClass::__set_state(array(
       '$version' => -27784,
       '$timestamp' => 1552751162598,
    )),
  )),
   'safety_summary' => 
  stdClass::__set_state(array(
     '996b95d0-4802-11e9-885b-0a6ce4a9ddca' => 
    stdClass::__set_state(array(
       '$version' => 30496,
       '$timestamp' => 1552751163000,
       'total_critical_failures' => 0,
       'total_warnings' => 0,
    )),
  )),
))
chrismarcellino@Chriss-MacBook-Pro nest-api-master $ 
`

**Comment by gboudreau** [comment]
Looks like you are the owner of a structure, `996b95d0-4802-11e9-885b-0a6ce4a9ddca`, which is indeed empty, but you are also `member` of another structure, `d87f21a0-ad1e-11e1-9ebb-1231391e8b17`, which is not returned here, and my guess is that your devices would be in that structure. Not sure how all this happened, or how we can load from the API a specific structure, if the default API call (`GET /v3/mobile/$user`) doesn't return it...

**Comment by chrismarcellino** [comment]
Odd. d87f21a0-ad1e-11e1-9ebb-1231391e8b17 is my actual structure that I can see when I log into the website (based on the URL.) The other one is nonsense.

**Comment by chrismarcellino** [comment]
Anyways, seems like this isn't an issue with this library. Thanks anyways.

**Comment by chrismarcellino** [comment]
FWIW, things just work fine when I use the owner (admin) account (and turn on 2FA) as opposed to a full access burner account.
