### ISSUE TITLE
406 Not Acceptable

### ISSUE THREAD

**Issue by joe248** [gboudreau/nest-api#98]
I've been using this class for a while to do some automation with my Nest.  Sometime within the past day it stopped working. When trying to log in I get:

```
PHP Fatal error:  Uncaught RuntimeException: Error: Response from request to https://home.nest.com/user/login is not valid JSON data. Response: <html><head><title>406 Not Acceptable</title></head><body bgcolor="white"><center><h1>406 Not Acceptable</h1></center><hr><center>nginx</center></body></html> in /home/homeassistant/custom/includes/nest.class.php:1276
Stack trace:
#0 /home/homeassistant/custom/includes/nest.class.php(1178): Nest->doRequest('POST', 'https://home.ne...', Array, true, Array)
#1 /home/homeassistant/custom/includes/nest.class.php(1106): Nest->doPOST('https://home.ne...', Array)
#2 /home/homeassistant/custom/includes/nest.class.php(136): Nest->login()
#3 /home/homeassistant/custom/scripts/update_nest_target_humidity.php(13): Nest->__construct()
#4 {main}
  thrown in /home/homeassistant/custom/includes/nest.class.php on line 1276
```

Anyone else getting this error?

**Comment by bauzer714** [comment]
Same for me - it looks like they deployed some changes. Can you confirm if you're a converted Google account or using Nest login?

**Comment by joe248** [comment]
No, I have not converted to a Google account

**Comment by bauzer714** [comment]
It appears that the endpoint has changed and reCAPTCHA has been implemented. I'm curious if the Google accounts are also having errors. 

![image](https://user-images.githubusercontent.com/13224936/68674452-e60fa280-0523-11ea-9f7a-824cc32890bb.png)

**Comment by joe248** [comment]
What client does this library emulate?  The iOS app?

**Comment by bauzer714** [comment]
Web browser

**Comment by joe248** [comment]
I see the browser user agent [in the login method](https://github.com/gboudreau/nest-api/blob/8ab160f0c2a37ac480fb9c7ee32f7ceab110eb2a/nest.class.php#L1051) but what is [this](https://github.com/gboudreau/nest-api/blob/8ab160f0c2a37ac480fb9c7ee32f7ceab110eb2a/nest.class.php#L57) then?

**Comment by gboudreau** [comment]
The line you mention in the login method is used for Google accounts only. The `Nest/2.1.3 CFNetwork/548.0.4` user-agent is used for Nest accounts, which was used in an old version of the mobile app. Maybe the mobile app login endpoint or content changed.

For Nest accounts, we send a POST to `https://home.nest.com/user/login`, not `https://home.nest.com/session`. If that last endpoint is used on the web, and requires a recaptcha, we can't use it.
If someone that still has a Nest account can trace what the iOS or Android app does, to login, and compare with https://github.com/gboudreau/nest-api/blob/8ab160f0c2a37ac480fb9c7ee32f7ceab110eb2a/nest.class.php#L1106, that might shed some light on what is happening.

Of note: Google Accounts are still working as expected, at least for me that set it up a few weeks ago.

**Comment by thecodingfrog** [comment]
same here with the 406 error

**Comment by doctorkb** [comment]
> For Nest accounts, we send a POST to `https://home.nest.com/user/login`, not `https://home.nest.com/session`. If that last endpoint is used on the web, and requires a recaptcha, we can't use it.
> If someone that still has a Nest account can trace what the iOS or Android app does, to login, and compare with

I'm happy to attempt this trace, but I have no idea on how to snoop on these connections via iOS.

I would like to migrate, but I have other integrations that aren't ready for WWGA yet...

**Comment by brendandebeasi** [comment]
They use certificate pinning on iOS, so I was unable to snoop the connection. That said it looks like the login page makes reference to Recaptcha, so I would assume that is locked down too now :(

**Comment by stuartajc** [comment]
I'm seeing the 406 error too, with a Nest account (not Google). Since I'm logging responses, I know that this error started between 1900-1910 UTC/GMT on 11 Nov 2019

**Comment by bauzer714** [comment]
All "Nest" account users are impacted. I noticed the Android app login references reCAPTCHA too. I'm guessing that any "Nest logins" in the short term future will require reCAPTCHA and any "fix" would be short lived. I'd be happy to try to look into this further, but I merged with Google login to restore my services.

**Comment by joe248** [comment]
Did you have any issues or lost functionality after moving to the Google login?

**Comment by doctorkb** [comment]
> Did you have any issues or lost functionality after moving to the Google login?

There is one big thing preventing me from switching today: I use my Nest as the conduit between my Vivint alarm and Hubitat Elevation to determine the home/away status by whether my alarm is armed or not... and those links will both break when I convert the Nest to a Google account.

I'd happily try faking the Nest login by copying a cookie from a successful web login...

**Comment by joe248** [comment]
I was able to get it working again by setting the `USER_AGENT` to `'Nest/5.0.0.23 (iOScom.nestlabs.jasper.release) os=11.0'` and `LOGIN_URL` to `'https://home.nest.com/session'`

Let me know if that works for you guys.

**Comment by a-b-s** [comment]
> I was able to get it working again by setting the `USER_AGENT` to `'Nest/5.0.0.23 (iOScom.nestlabs.jasper.release) os=11.0'` and `LOGIN_URL` to `'https://home.nest.com/session'`
> 
> Let me know if that works for you guys.

Changing  the parameters in the nest.class.php file to the suggested user agent and login url, restored functionality!

**Comment by vdleun** [comment]
> Let me know if that works for you guys.

To confirm: this change also works for me. Thank you!

**Comment by thecodingfrog** [comment]
> I was able to get it working again by setting the `USER_AGENT` to `'Nest/5.0.0.23 (iOScom.nestlabs.jasper.release) os=11.0'` and `LOGIN_URL` to `'https://home.nest.com/session'`
> 
> Let me know if that works for you guys.

Yep that works, you're the man!

**Comment by gboudreau** [comment]
Super, thanks @joe248.

**Comment by doctorkb** [comment]
> I was able to get it working again by setting the `USER_AGENT` to `'Nest/5.0.0.23 (iOScom.nestlabs.jasper.release) os=11.0'` and `LOGIN_URL` to `'https://home.nest.com/session'`
> 
> Let me know if that works for you guys.

Works here, too.  Thank you SO much!

**Comment by stuartajc** [comment]
> I was able to get it working again by setting the `USER_AGENT` to `'Nest/5.0.0.23 (iOScom.nestlabs.jasper.release) os=11.0'` and `LOGIN_URL` to `'https://home.nest.com/session'`
> 
> Let me know if that works for you guys.

Brilliant, works great. Thanks
